slam_toolbox:
  ros__parameters:
    use_sim_time: false

    mode: localization #mapping
    map_file_name: /home/lota/ros2_ws/my_map.yaml

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan_merged
    odom_topic: /odometry/filtered

    publish_tf: true
    transform_publish_period: 0.05

    resolution: 0.05
    max_laser_range: 10.0

    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    
    throttle_scans: 2
    scan_queue_size: 1
    
    map_start_pose: [0.0, 0.0, 0.0]


